### ISSUE TITLE
Default click-to-open-card behavior changed

### ISSUE THREAD

**Issue by wvconnors** [laander/trello-birdseye#1]
Hi,
Doesn't seem like this project is actively being developed, but in case someone is out there: enabling bird's eye seems to change clicking a card in a list from opening the card to opening the quick edit panel (normally accessed by clicking pencil edit icon on right side of card in list). The only way I can find to actually open a card in bird's eye mode is to first drag the card to a new list or position, and then clicking will open it. 
This is less than ideal. Not sure if the behavior change is a purposeful feature, but I would like to use the default card opening behavior. I would just fork my own, but not being very knowledgeable in web dev, I cannot see where in the javascript or css is making things change. Any help and/or insight would be appreciated!

**Comment by leocb** [comment]
I submitted a fix, simple stuff on CSS, just wait for the author to accept

**Comment by laander** [comment]
@wvconnors @leocb Sorry for the lack of response, I honestly missed it in the flood Github notifications. 

The purpose with the inline editing as default click behaviour was to make it quicker to perform simple actions, but you're right, it's actually more in the way than useful. Merged the PR (https://github.com/laander/trello-birdseye/pull/2) and will release shortly 👍  

Thanks for feedback!

**Comment by laander** [comment]
Aaand it's out, closing this issue 🚀
