### ISSUE TITLE
Firefox version ?

### ISSUE THREAD

**Issue by pabuisson** [laander/trello-birdseye#5]
Hey laander, did you consider making this cross-compatible to also run on Firefox? Given the current codebase and manifest, I don't think this would be much work. And I personally would use it (Firefox is my main browser, I only switch to Chrome-based browsers from time to time).

**Comment by laander** [comment]
Hi @pabuisson , I unfortunately don't have the time for it currently, but you're super welcome to fork the code and give it a shot! Also, I've never made any Firefox extensions - are the browser API's roughly the same? :)

**Comment by pabuisson** [comment]
Hi @laander! I might do this someday, but not now, I'm changing jobs and city very soon so I have a lot on my plate at the moment. 

As for the APIs, they're pretty similar. I'd say Firefox APIs are richer than Chrome's, Firefox has been doing a lot of work on the APIs implementation since Firefox Quantum. I'm currently in the process of porting my own addon to Chrome and am facing some challenges (can't declare both a browserAction and a pageAction in Chrome, for instance), but eventually, most of the code seems compatible.
